packages/libpciaccess/build.sh
packages/libpciaccess/ndk.patch
packages/xf86-video-dummy/build.sh
packages/xf86-video-dummy/dummy.xorg.conf
packages/xf86-video-dummy/ndk.patch
packages/xorg-server/build.sh
packages/xorg-server/disable-modesetting.patch
packages/xorg-server/kd.patch
packages/xorg-server/platform_noop.c
packages/xorg-server/statifiing-all-modules.patch
packages/xorg-server/stubmain.c.patch
packages/xorg-server/xf86AutoConfig.c.patch
packages/xorg-server/xorg-server-1.20.1_Xext_xf86bigfont.c.patch
packages/xorg-server/xorg-server-1.20.1_hw_xfree86_common_compiler.h.patch
packages/xorg-server/xorg-server-1.20.1_hw_xfree86_common_xf86Config.c.patch
packages/xorg-server/xorg-server-1.20.1_hw_xfree86_os-support_linux_lnx_acpi.c.patch
packages/xorg-server/xorg-server-1.20.1_hw_xfree86_os-support_linux_lnx_kmod.c.patch
packages/xorg-server/xorg-server-1.20.1_hw_xfree86_parser_scan.c.patch
packages/xorg-server/xorg-server-1.20.1_hw_xfree86_parser_write.c.patch
packages/xorg-server/xorg-server-1.20.1_hw_xfree86_xorg-wrapper.c.patch
packages/xorg-server/xorg-server-1.20.1_include_site.h.patch
packages/xorg-server/xorg-server-1.20.1_os_access.c.patch
packages/xorg-server/xorg-server-1.20.1_os_backtrace.c.patch
packages/xorg-server/xorg-server-1.20.1_os_connection.c.patch
packages/xorg-server/xorg-server-1.20.1_os_osinit.c.patch
packages/xorg-server/xorg-server-1.20.1_os_utils.c.patch
packages/xorg-server/xorg-server-1.20.1_xkb_ddxLoad.c.patch

I think it will be useful. Also for now I'm trying to output image from Xorg to Activity surface via shared memory.

Adding xorg-server package with full Xorg and dummy driver

---

packages/plotutils/build.sh
packages/plotutils/libpng-fix.patch

Requested in https://github.com/termux/x11-packages/issues/52.

new package: plotutils

---

packages/libart-lgpl/build.sh
packages/libgnomecanvas/build.sh
packages/poppler-glib/build.sh
packages/poppler-glib/gstrtod.cc.patch
packages/poppler-glib/poppler-Form.cc.patch
packages/xournal/build.sh
packages/xournal/xo-shapes.c.patch

Implements https://github.com/termux/x11-packages/issues/18.

new package: xournal

---

.gitlab-ci.yml
packages/libfm-extra/archivers.list.patch
packages/libfm-extra/build.sh
packages/libfm-extra/fix-hardcoded-paths.patch
packages/libfm-extra/terminals.list.patch
packages/libfm/archivers.list.patch
packages/libfm/build.sh
packages/libfm/fix-hardcoded-paths.patch
packages/libfm/terminals.list.patch
packages/lxmenu-data/build.sh
packages/menu-cache/build.sh
packages/pcmanfm/build.sh

Requested in https://github.com/termux/x11-packages/issues/40

new package: pcmanfm

---

packages/dwm/build.sh
packages/dwm/config.h
packages/dwm/config.mk.patch

added dwm package

---

packages/libvte/build.sh
packages/libvte/libvte-src-vte-cc.patch
packages/xfce4-terminal/build.sh

Tested on Android 9 device.
Fixes issue #158.

Add xfce4-terminal and required dependency libvte.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/termux/x11-packages/203)

Fix typo and grammar in README.md

---

packages/wmaker/build.sh

wmaker: remove dynamic libomp dependency

---

packages/tumbler/build.sh

I will also be adding Ristretto image viewer in a PR... and it needs tumbler to work properly

Add package: tumbler

---

packages/ristretto/build.sh

Add package: ristretto

---

packages/gigolo/build.sh

Add package: gigolo

---

packages/geany-plugins/build.sh

Add package: geany-plugins

---

packages/qt5-qtmultimedia/build.sh
packages/qt5-qtmultimedia/detect_libs_without_pkg_config.patch
packages/qt5-qtmultimedia/pulse_audio_without_glib.patch

note this is not really a feature-rich module (no gstreamer)
let's see if it will work for #241

add qtmultimedia submodule

---

packages/qt5-qttools/assistant.desktop
packages/qt5-qttools/build.sh
packages/qt5-qttools/designer.desktop
packages/qt5-qttools/linguist.desktop
packages/qt5-qttools/qdbusviewer.desktop
packages/qt5-qttools/qt5-qttools-cross-tools.subpackage.sh

this package contains the full set of tools
with desktop entries for the common tools

add qt5-qttools package (assistant, linguist, designer, etc.)

---

packages/zenity/Makefile.am.patch
packages/zenity/build.sh
packages/zenity/main.c.patch

I'll be adding the package marco here soon..

add package:zenity

---

packages/qt5-qtquickcontrols2/build.sh

add Qt Quick Controls 2 package

---

packages/libmatekbd/build.sh
packages/libmatekbd/genmarshal.patch

I will be adding other mate components to this PR one by one..

Add package:libmatekbd

---

start-builder.sh

in line with the main `termux-packages` repo

use sudo only if environment variable says so

---

packages/kirigami2/0001-Revert-Watch-for-language-change-events-and-forward-.patch
packages/kirigami2/build.sh
packages/kirigami2/fix_incomplete_types.patch
packages/kirigami2/no_opengl.patch
packages/kirigami2/treat_android_as_linux.patch
packages/kirigami2/without_accessibility.patch
packages/kirigami2/without_qt_graphical_effects.patch

this enables the build of sample Kirigami Gallery app. With brief testing, everything seems to be functional (minus the visuals which are removed because of lacking of OpenGL)

add kirigami2 package without OpenGL

---

packages/lyx/build.sh

aarch64 build passed. tested on my own device and it seems working fine
let's see about other archs

add Lyx package. fix #152

---

packages/at-spi2-atk/build.sh

One of the depenencies of gnome shell #314

Add package: at-spi2-atk

---

packages/karchive/build.sh
packages/kauth/build.sh
packages/kcodecs/build.sh
packages/kconfig/build.sh
packages/kcoreaddons/build.sh
packages/kcoreaddons/no_redefinition_kuser_unix.patch
packages/ki18n/build.sh
packages/kitemmodels/build.sh
packages/kitemviews/build.sh
packages/kwidgetsaddons/build.sh

These are straightforward to be ported and can be cross compiled easily

Add more packages from KDE Frameworks 5

---

packages/papirus-icon-theme/build.sh

Papirus is a very popular icon theme available in all Linux distros

add papirus-icon-theme

---

packages/sdl-ttf/build.sh

A companion library to SDL for working with TrueType (tm) fonts.

New package: sdl-ttf

---

packages/roxterm/build.sh

Roxterm is a perfect alternative to aterm

add package: roxterm

---

packages/libquazip/build.sh

Quazip is a qt lib for zip archives

add lib: libquazip

---

packages/debpac/build.sh
packages/debpac/debpac.pro.patch

debpac is a simple application to create deb packages, you can save the configuration of a .json file, a good alternative to making packages from the terminal.

add package: debpac

---

packages/scrot/build.sh

scrot is a very minimal screenshot for X
it would be great if this added since you can simply screenshot your X using `scrot` using the Terminal without arguments and will automatically capture your screen into png file

New Package: scrot

---

packages/tilda/build.sh

ok this time i fixed everythig, and its work fine

add package tilda

---

packages/heimer/build.sh

Heimer It is an application to create diagrams and concept maps, excellent for students and designers of these things.

add package: heimer

---

packages/trojita/build.sh

Trojita is a mail client made in qt

add package: trojita

---

packages/gtk2-engines-murrine/build.sh

This is just a test, I don't know if it works.

add package : gtk2-engines-murrine

---

packages/chocolate-doom/build.sh

i'm changing the ownership name since i didn't notice that past few months that i changed maintainership on some packages

chocolate doom: change maintainership

---

packages/tilda/build.sh

something is wrong with tilde and it need to rebuild

fix [job] error

---

packages/picom/build.sh
packages/picom/log.c.patch
packages/picom/log.h.patch

currently picom is not working, these patches fix that bug.

picom: fix timespec error

---

packages/tsmuxergui/build.sh

new package: tsmuxergui

---

packages/kermit/build.sh

as promised, I have come to bring it : D

Kermit Terminal 🐸

---

packages/wkhtmltopdf/build.sh

new package: wkhtmltopdf

---

packages/xfce4-session/build.sh

xfce4-session: depends on pango

---

packages/xfce-theme-manager/build.sh
packages/xfce-theme-manager/use_termux_prefix.patch

xfce-theme-manager is a very simple interface to customize xfce

add package: xfce-theme-manager (#353)

---

packages/wxwidgets/build.sh
packages/wxwidgets/include-wx-android-chkconf.h.patch
packages/wxwidgets/include-wx-android-config_android.h.patch
packages/wxwidgets/src-common-filename.cpp.patch
packages/wxwidgets/src-unix-mimetype.cpp.patch

Closes termux/termux-packages#7729.

new package: wxwidgets

---

packages/virglrenderer/build.sh
packages/virglrenderer/src-vrend_winsys_gbm.h.patch
packages/virglrenderer/vtest-vtest_protocol.h.patch

Closes termux/termux-packages#7744.

new package: virglrenderer

---

packages/wxwidgets/build.sh

Addresses https://github.com/termux/x11-packages/issues/408#issuecomment-999608603.

wxwidgets: Install `include/wx/android`

---

packages/spek/build.sh
packages/spek/src-spek-preferences.cc.patch
packages/spek/src-spek-preferences.h.patch

new package: spek

---

packages/emacs-x/build.sh

emacs-x: Enable JSON support

---

packages/cuse/build.sh
packages/cuse/configure.ac.patch
packages/cuse/src-CuSE.cxx.patch
packages/cuse/src-sequencer.h.patch

new package: cuse

---

packages/mumble-server/build.sh
packages/mumble-server/scripts-murmur-user-wrapper.patch
packages/mumble-server/src-murmur-UnixMurmur.cpp.patch

Closes https://github.com/termux/termux-packages/issues/3766.

new package: mumble-server

---

packages/sdl2/build.sh

sdl2: Create `libSDL2.so` symlink

---

packages/sdl2/build.sh

sdl2: Enable OpenGL support

---

packages/xclip/build.sh

close (#641)
Signed-off-by: Yisus7u7 <dev.yisus@hotmail.com>

add package: xclip

---

packages/adwaita-qt/build.sh
packages/gnome-themes-extra/build.sh
packages/gnome-themes-extra/gtk2-engines-adwaita-static.subpackage.sh
packages/gnome-themes-extra/gtk2-engines-adwaita.subpackage.sh

add packages: adwaita-qt and gnome-themes-extra

---

packages/tinyemu/001-fix-hardcoded-paths.patch
packages/tinyemu/002-fix-time_nsec-defs.patch
packages/tinyemu/003-Makefile.patch
packages/tinyemu/004-Makefile.patch32
packages/tinyemu/build.sh

https://github.com/termux/termux-packages/issues/9815
Note: As there may have some of duplicates of emulator that doing same thing, __Please close this if this package break packaging policy.__

New Package: tinyemu

---

packages/synaptic/build.sh
packages/synaptic/no_pthread.patch
packages/synaptic/no_root_and_termux_support.patch

It works properly.
Thanks to @Maxython for the help.

new package: synaptic
