scripts/bintray-add-package.py

`.split(",")` will give a list even if TERMUX_PKG_LICENSE doesn't contain a "," so this should work

bintray-add-package.py: handle comma separated license list

---

packages/xsel/build.sh

Hey all, I would like to add this package to the distribution. It seems
to be building fine only with this error at the end of the build:
```
ERROR: No LICENSE file was installed for xsel
```
Also, I'm not sure that I've had to write my own version of the
functions `termux_step_make` and `termux_step_make_install` but I guess
that since I've overridden `termux_step_extract_package`, this was
necessary as well.
For reference, the license upstream is:
https://github.com/kfish/xsel/blob/master/COPYING

[WIP] add package xsel

---

packages/bochs/build.sh
packages/bochs/bx_debug-Makefile.in.patch
packages/bochs/configure.patch
packages/bochs/gui-term.cc.patch
packages/bochs/iodev-network-slirp-misc.cc.patch

**Package description**
Bochs is a highly portable open source IA-32 (x86) PC emulator and debugger written in C++.
Although there are already some Android ports for bochs, this version has a GUI assembler debugger that is helpful for operating system development and research.
Screenshot of running Linux0.11 in bochs:
**Link to home page and sources**
1. Home page: http://bochs.sourceforge.net/
2. Source code:https://sourceforge.net/projects/bochs/files/bochs/
Problem:
A warning is show when using GUI debugger(screenshot above) 
Any reason for disable X11 thread support?

new package: bochs

---

packages/netsurf/build.sh

Tested on Android 9 device.
Currently I had to disable Javascript support ("Duktape") because I wasn't able to figure out how to build the required nsgenbind tool so that it can be executed on the *host* (it is used during the build process only). 
Shouldn't be a large issue though because Netsurf's Javascript support is very rudimentary anyway and will not really be missed.

Add web browser netsurf.

---

start-builder.sh

Avoid using custom Docker image for official packages.

start-builder.sh: use official Termux build environment

---

packages/wmaker/build.sh

WindowMaker is an X11 window manager that reproduces the look and feel of the NeXTSTEP user interface.
This is something I use, that I thought you might want to add.

Add wmaker package

---

packages/chocolate-doom/build.sh

This package allows users to run WAD files such as Doom, Hexen, Heretic, etc,
Of course, for better experience, Samsung DeX or External VNC Display with mouse and keyboard is recommended

Add package: chocolate-doom

---

packages/qt5-qtbase/build.sh
packages/qt5-qtbase/qmake.host.conf
packages/qt5-qtbase/qplatformdefs.host.h
packages/qt5-qtbase/qt5-qtbase-cross-tools.subpackage.sh
packages/qt5-qtdeclarative/build.sh
packages/qt5-qtdeclarative/qt5-qtdeclarative-cross-tools.subpackage.sh

adding a dedicated termux host building spec (`linux-g++` is not working when building `qttools` because of the messy include chain hacked by us for termux which resulted in redefinition of structs). this `termux-host` seems working
additionally, making the host tools arch independent since it is for the host and not for termux

updates qtbase and qtdeclarative for host building

---

packages/otter-browser/build.sh
packages/qt5-qtlocation/build.sh
packages/qt5-qtmultimedia/build.sh
packages/qt5-qtmultimedia/detect_libs_without_pkg_config.patch
packages/qt5-qtmultimedia/gst_include_path.patch
packages/qt5-qtsensors/build.sh
packages/qt5-qtsensors/no_librt.patch
packages/qt5-qtwebchannel/build.sh
packages/qt5-qtwebkit/0001-Remove-invalid-g_object-declarations-to-fix-build-wi.patch
packages/qt5-qtwebkit/build.sh
packages/qt5-qtwebkit/icu-68.patch
packages/qt5-qtwebkit/no_execinfo_header.patch
packages/qt5-qtwebkit/tools_qttestbrowser_launcherwindow_no_opengl.patch
packages/qt5-qtwebkit/webkit-bwo141288.patch
packages/qt5-qtwebsockets/build.sh

- Multimedia module has been fixed to use GStreamer properly (tested working with video and audio playback)
- Qt Location, Qt Sensors are added as dependencies of Qt WebKit module
- Qt WebSockets, Qt WebChannel are added (during an attempt to use WebKit 2)
- [`otter-browser`](https://github.com/OtterBrowser/otter-browser/) is added 
- Video playback is NOT working in `otter-browser` at the moment
- QtWebKit is based on an old webkit codebase and has unpatched security vulnerabilities. Use it in restricted environment and do not transmit sensitive data

add otter-browser, QtWebKit and their dependencies

---

packages/qt5-qtbase/build.sh
packages/qt5-qtbase/glib_gtk_detection_without_pkgconfig.patch
packages/qt5-qtbase/qmake.conf
packages/qt5-qtbase/qmake.host.conf
packages/qt5-qtbase/qt5-qtbase-gtk-platformtheme.subpackage.sh

The ugliness of the include directories is due to the Qt
build system in this version refuses to use pkg-config.
To use GTK+3 platform theme, install the new subpackage,
```bash
export QT_QPA_PLATFORMTHEME=gtk3
```
This should make Qt applications look more _native_ under GTK-based DE

Build Qt with glib and build GTK+ platform theme plugin

---

packages/otter-browser/3rdparty_fhs_termux_prefix.patch
packages/otter-browser/build.sh

haven't noticed any difference but those hardcoded FHS paths need to be patched

fix otter-browser 3rd party paths

---

packages/mesa-demos/LICENSE
packages/mesa-demos/build.sh

This package provides useful utilities to test and get information about
available OpenGL support such as glxinfo and glxgears.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>

add package: mesa-demos

---

packages/devilspie/build.sh
packages/devilspie/fix_manpage_lintian_warnings.patch
packages/devilspie/fix_memleak_in_my_wnck_get_viewport_start.patch
packages/devilspie/fix_using_deprecated_wnck_functions.patch
packages/devilspie/remove_unavailable_options_from_manpage.patch

This is a user daemon utility that reads configuration files in lisp for
matching X11 windows and performing actions on them.
For example, I have this file:
~/.devilspie/undecorate.ds
with this contents:
```
(if (or (is (window_class) "qterminal") (is (window_class) "Xfce4-terminal"))
(undecorate)
)
```
With the daemon launched from my xstartup, when a window matching the
class "qterminal" or "Xfce4-terminal" is opened, it will remove window
manager decorations from it giving me a borderless window without a
title bar.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>

new package: devilspie

---

packages/x11vnc/build.sh

Missing Library: `libxcursor`, `libcairo`

x11vnc: Add missing library

---

packages/qt-creator/build.sh

Now the output of ` readelf --dynamic /data/data/com.termux/files/usr/lib/qtcreator/plugins/libClangTools.so` shows `libc++_shared.so` is the shared library needed.
```plain
0x0000000000000001 (NEEDED)             Shared library: [libandroid-shmem.so]
0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
0x0000000000000001 (NEEDED)             Shared library: [libDebugger.so]
0x0000000000000001 (NEEDED)             Shared library: [libCppTools.so]
0x0000000000000001 (NEEDED)             Shared library: [libCore.so]
0x0000000000000001 (NEEDED)             Shared library: [libProjectExplorer.so]
0x0000000000000001 (NEEDED)             Shared library: [libTextEditor.so]
0x0000000000000001 (NEEDED)             Shared library: [libyaml-cpp.so.4]
0x0000000000000001 (NEEDED) …
```

force linking libc++_shared for ClangTools, fixing #391

---

packages/mate-applet-brisk-menu/build.sh

brisk menu is a modern menu for mate, similar to the gnome menu
It has two modes (classic and dash)
As there is no dconf configuration interface for termux, it must be configured by manually editing the xml file
`/data/data/com.termux/files/usr/share/glib-2.0/schemas/com.solus-project.brisk-menu.gschema.xml`

add package: brisk-menu

---

packages/parole/build.sh

Parole is the official music player of XFCE, I compiled it and it works very well, the videos go fluid even in vnc, this is a great achievement, it can be replaced mpv-x at last

add package: Parole media player

---

packages/tint2/build.sh

- The github one is fairly outdated so moving the source code URL to gitlab which contains the new version
- Changing maintainership as github account does not exists anymore

tint2: update package

---

packages/flacon/build.sh

out of previous `taglib` shared libraries.

flacon: Get rid of references to leaked libunwind

---

packages/tigervnc/build.sh

Revbump is unnecessary due to build failure.

tigervnc: Link against compiler-rt builtins
